export const pets= [
  {
    id: 1,
    type: 'Собака',
    weight: 6,
    character: 'Активный',
    age: 2,
    gender: 'Мальчик',
    fur: 'Длинная',
    description: 'Дружелюбный и энергичный, любит прогулки',
    images: ['https://petsi.net/images/dogbreed/pomeranian.jpg'],
    status: 'В приюте',
    other: ['Для семьи с детьми'],
    health: 'Здоровая',
  },
  {
    id: 2,
    type: 'Кошка',
    weight: 4,
    character: 'Спокойный',
    age: 3,
    gender: 'Девочка',
    fur: 'Короткая',
    description: 'Ласковая и тихая, любит спать на руках',
    images: ['https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg'],
    status: 'На передержке',
    other: ['Ладит с кошками'],
    health: 'Здоровая',
  },
  {
    id: 3,
    type: 'Собака',
    weight: 20,
    character: 'Активный',
    age: 4,
    gender: 'Мальчик',
    fur: 'Короткая',
    description: 'Верный охранник, нуждается в активной семье',
    images: ['https://upload.wikimedia.org/wikipedia/commons/6/6e/Golde33443.jpg'],
    status: 'В приюте',
    other: ['Ладит с собаками'],
    health: 'Подготовка к операции',
  },
  {
    id: 4,
    type: 'Кошка',
    weight: 3,
    character: 'Спокойный',
    age: 1,
    gender: 'Девочка',
    fur: 'Длинная',
    description: 'Нежная и аккуратная, немного пугливая',
    images: ['https://upload.wikimedia.org/wikipedia/commons/b/b6/Felis_catus-cat_on_snow.jpg'],
    status: 'В добрых руках',
    other: ['Для семьи с детьми'],
    health: 'Здоровая',
  },
  {
    id: 5,
    type: 'Собака',
    weight: 12,
    character: 'Активный',
    age: 3,
    gender: 'Девочка',
    fur: 'Короткая',
    description: 'Весёлая и контактная, обожает играть',
    images: ['https://upload.wikimedia.org/wikipedia/commons/1/1b/Dog_on_the_beach.jpg'],
    status: 'В приюте',
    other: ['Ладит с собаками'],
    health: 'На лечение',
  },
  {
    id: 6,
    type: 'Кошка',
    weight: 5,
    character: 'Спокойный',
    age: 5,
    gender: 'Мальчик',
    fur: 'Короткая',
    description: 'Спокойный и мудрый кот, любит тишину',
    images: ['https://upload.wikimedia.org/wikipedia/commons/a/a3/June_odd-eyed-cat.jpg'],
    status: 'На передержке',
    other: ['Ладит с кошками'],
    health: 'Здоровая',
  },
  {
    id: 7,
    type: 'Собака',
    weight: 25,
    character: 'Активный',
    age: 6,
    gender: 'Мальчик',
    fur: 'Длинная',
    description: 'Крупный и добрый пёс, отличный друг',
    images: ['https://upload.wikimedia.org/wikipedia/commons/0/0b/Siberian_Husky_pho.jpg'],
    status: 'В приюте',
    other: ['Для семьи с детьми'],
    health: 'Здоровая',
  },
  {
    id: 8,
    type: 'Кошка',
    weight: 2,
    character: 'Активный',
    age: 1,
    gender: 'Девочка',
    fur: 'Короткая',
    description: 'Игривая и любопытная малышка',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/4c/Push_van_cat.jpg'],
    status: 'В приюте',
    other: ['Ладит с собаками'],
    health: 'Здоровая',
  },
  {
    id: 9,
    type: 'Собака',
    weight: 18,
    character: 'Спокойный',
    age: 5,
    gender: 'Мальчик',
    fur: 'Короткая',
    description: 'Спокойный и уравновешенный, идеально для дома',
    images: ['https://upload.wikimedia.org/wikipedia/commons/9/9f/Dog_labrador.jpg'],
    status: 'В добрых руках',
    other: ['Для семьи с детьми'],
    health: 'Здоровая',
  },
  {
    id: 10,
    type: 'Кошка',
    weight: 4,
    character: 'Спокойный',
    age: 4,
    gender: 'Девочка',
    fur: 'Длинная',
    description: 'Пушистая и ласковая кошка',
    images: ['https://upload.wikimedia.org/wikipedia/commons/0/0c/Cat_orange_fur.jpg'],
    status: 'В приюте',
    other: ['Ладит с кошками'],
    health: 'На лечение',
  }
];